# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-20 07:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_auto_20181220_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
