# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-21 12:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_table_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='alignment',
            field=models.CharField(choices=[('L', 'Left'), ('R', 'Right')], default='L', max_length=1),
        ),
    ]
