# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-16 20:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_productcategory_parent_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='unit',
        ),
    ]
