# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-10 09:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('ingredients', '0002_auto_20181210_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='unit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='products.Unit'),
            preserve_default=False,
        ),
    ]
